<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.westarenergy.com/EBM/CreateItem/V1.0"
                xmlns:tns="http://xmlns.oracle.com/Enterprise/FSCM/schema/ITEM_SYNC.VERSION_1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:cmn="http://xmlns.westarenergy.com/core/CommonTypes/V1.0"
                xmlns:ns4="http://xmlns.westarenergy.com/EBO/Item/V1.0"
                xmlns:ns1="http://xmlns.westarenergy.com/WSDL/PPLSFT_CRUD_Item_ABCS_prov/V1.0"
                xmlns:fault="http://xmlns.westarenergy.com/Faults/CommonFaults/V1.0"
                xmlns:ns3="http://xmlns.westarenergy.com/EBM/CommonEBMHeader/V1.0"
                xmlns:ns5="http://xmlns.oracle.com/Enterprise/FSCM/service/ITEM_SYNC"
                xmlns:wsp="http://schemas.xmlsoap.org/ws/2002/12/policy"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns6="http://www.w3.org/2000/xmlns/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/WestarEnergy/ABCS/wsdl/PPLSFT_CRUD_Item_ABCS_prov.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CreateItemRequest"
                                       namespace="http://xmlns.westarenergy.com/EBM/CreateItem/V1.0"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="oramds:/apps/WestarEnergy/PPLSFT/wsdl/ITEM_SYNC.1.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ITEM_SYNC"
                                       namespace="http://xmlns.oracle.com/Enterprise/FSCM/schema/ITEM_SYNC.VERSION_1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE NOV 10 15:29:56 CST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ITEM_SYNC>
      <tns:FieldTypes>
        <tns:MASTER_ITEM_EVW>
          <tns:INV_ITEM_ID type=""/>
          <tns:ITM_STATUS_CURRENT type=""/>
          <tns:DESCR60 type=""/>
        </tns:MASTER_ITEM_EVW>
        <tns:INV_ITM_UOM_EVW class="">
          <tns:SETID/>
          <tns:INV_ITEM_ID type=""/>
          <tns:UNIT_OF_MEASURE type=""/>
          <tns:DFLT_UOM_REQ type=""/>
        </tns:INV_ITM_UOM_EVW>
        <tns:PUR_ITM_ATR_EVW>
          <tns:SETID/>
          <tns:DESCR/>
          <tns:PRICE_LIST/>
          <tns:DESCR254_MIXED type=""/>
        </tns:PUR_ITM_ATR_EVW>
        <tns:ITEM_MFG_EVW class="">
          <tns:SETID type=""/>
        </tns:ITEM_MFG_EVW>
      </tns:FieldTypes>
      <tns:MsgData>
        <xsl:for-each select="">
          <tns:Transaction>
            <tns:MASTER_ITEM_EVW>
              <tns:SETID>
                <xsl:value-of select='"SHARE"'/>
              </tns:SETID>
              <tns:INV_ITEM_ID>
                <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ItemId"/>
              </tns:INV_ITEM_ID>
              <tns:ITM_STATUS_CURRENT>
                <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ItemStatusCurrent"/>
              </tns:ITM_STATUS_CURRENT>
              <tns:DESCR/>
              <tns:DESCR60>
                <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:Description"/>
              </tns:DESCR60>
              <tns:INV_ITM_UOM_EVW>
                <tns:SETID>
                  <xsl:value-of select='"SHARE"'/>
                </tns:SETID>
                <tns:INV_ITEM_ID>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ItemId"/>
                </tns:INV_ITEM_ID>
                <tns:UNIT_OF_MEASURE>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:UnitOfMeasure/ns4:UnitOfMeasure"/>
                </tns:UNIT_OF_MEASURE>
                <tns:DFLT_UOM_STOCK>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:UnitOfMeasure/ns4:UnitOfMeasureDefaultUse"/>
                </tns:DFLT_UOM_STOCK>
                <tns:DFLT_UOM_REQ>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:UnitOfMeasure/ns4:UnitOfMeasureDefaultUse"/>
                </tns:DFLT_UOM_REQ>
                <tns:LAST_DTTM_UPDATE/>
              </tns:INV_ITM_UOM_EVW>
              <tns:PUR_ITM_ATR_EVW>
                <tns:SETID>
                  <xsl:value-of select='"SHARE"'/>
                </tns:SETID>
                <tns:INV_ITEM_ID>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ItemId"/>
                </tns:INV_ITEM_ID>
                <tns:DESCR>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:Description"/>
                </tns:DESCR>
                <tns:DESCRSHORT>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:Description"/>
                </tns:DESCRSHORT>
                <tns:DESCR254_MIXED>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:Description"/>
                </tns:DESCR254_MIXED>
              </tns:PUR_ITM_ATR_EVW>
              <tns:ITEM_MFG_EVW class="{/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ItemId}">
                <tns:SETID>
                  <xsl:value-of select='"SHARE"'/>
                </tns:SETID>
                <tns:INV_ITEM_ID>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ItemId"/>
                </tns:INV_ITEM_ID>
                <tns:MFG_ID>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ManufacturerId"/>
                </tns:MFG_ID>
                <tns:MFG_ITM_ID>
                  <xsl:value-of select="/ns0:CreateItemRequest/ns0:DataArea/ns0:CreateItemRequestData/ns4:ManufacturerItemId"/>
                </tns:MFG_ITM_ID>
              </tns:ITEM_MFG_EVW>
            </tns:MASTER_ITEM_EVW>
          </tns:Transaction>
        </xsl:for-each>
      </tns:MsgData>
    </tns:ITEM_SYNC>
  </xsl:template>
</xsl:stylesheet>
