<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Item_EBS"
     targetNamespace="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="Item_EBS_ref">
        <plnk:role name="ItemCRUDPortType" portType="tns:ItemCRUDPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0" location="Item_EBS.wsdl"/>
</wsdl:definitions>
