<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="Item_EBS"
     targetNamespace="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0"
     xmlns:ebm1="http://xmlns.westarenergy.com/EBM/CreateItem/V1.0"
     xmlns:fault="http://xmlns.westarenergy.com/Faults/CommonFaults/V1.0"
    >
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.westarenergy.com/EBM/CreateItem/V1.0" schemaLocation="oramds:/apps/WestarEnergy/EBM/CreateItem_EBM_V1.0.xsd"/>
            <import namespace="http://xmlns.westarenergy.com/Faults/CommonFaults/V1.0" schemaLocation="oramds:/apps/WestarEnergy/Common/xsd/FaultTypes_V1.0.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CreateItemRequestMessage">
        <wsdl:part name="payload" element="ebm1:CreateItemRequest"/>
    </wsdl:message>
    <wsdl:message name="CreateItemResponseMessage">
        <wsdl:part name="payload" element="ebm1:CreateItemResponse"/>
    </wsdl:message>
    <wsdl:message name="GeneralFaultMessage">
        <wsdl:part name="fault" element="fault:GeneralFault"/>
    </wsdl:message>
    <wsdl:portType name="ItemCRUDPortType">
        <wsdl:operation name="CreateItem">
            <wsdl:input message="tns:CreateItemRequestMessage"/>
            <wsdl:output message="tns:CreateItemResponseMessage"/>
            <wsdl:fault name="GeneralFault" message="tns:GeneralFaultMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
