<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://xmlns.westarenergy.com/WSDL/MX_CreateItem_ABCS_req/V1.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://xmlns.westarenergy.com/WSDL/MX_CreateItem_ABCS_req/V1.0"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:ns1="http://xmlns.westarenergy.com/Common/Logging/V1.0"
     xmlns:ns2="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0"
    >
    <plnk:partnerLinkType name="mx_createitem_abcs_req_client_ep">
        <plnk:role name="ItemCRUDPortType" portType="tns:ItemCRUDPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.westarenergy.com/WSDL/MX_CreateItem_ABCS_req/V1.0" location="oramds:/apps/WestarEnergy/ABCS/wsdl/MX_CreateItem_ABCS_req.wsdl"/>
    <wsdl:import namespace="http://xmlns.westarenergy.com/WSDL/Item_EBS/V1.0" location="Item_EBS.wsdl"/>
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.westarenergy.com/Common/Logging/V1.0" schemaLocation="oramds:/apps/WestarEnergy/Events/xsd/LogEvent_V1.0.xsd"/>
        </xsd:schema>
    </wsdl:types>
</wsdl:definitions>
