<?xml version="1.0" encoding="UTF-8"?>
<definitions
    
     targetNamespace="http://xmlns.westarenergy.com/WSDL/PPLSFT_CRUD_Item_ABCS_prov/V1.0"
     xmlns="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.westarenergy.com/WSDL/PPLSFT_CRUD_Item_ABCS_prov/V1.0"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:cmn="http://xmlns.westarenergy.com/core/CommonTypes/V1.0"
     xmlns:cit="http://xmlns.westarenergy.com/EBM/CreateItem/V1.0"
     xmlns:fault="http://xmlns.westarenergy.com/Faults/CommonFaults/V1.0"
    >
    <types>
        <xsd:schema>
            <xsd:import namespace="http://xmlns.westarenergy.com/EBM/CreateItem/V1.0" schemaLocation="oramds:/apps/WestarEnergy/EBM/CreateItem_EBM_V1.0.xsd"/>
            <xsd:import namespace="http://xmlns.westarenergy.com/Faults/CommonFaults/V1.0" schemaLocation="oramds:/apps/WestarEnergy/Common/xsd/FaultTypes_V1.0.xsd"/>
        </xsd:schema>
    </types>
    <message name="CreateItemRequestMessage">
        <part name="payload" element="cit:CreateItemRequest"/>
    </message>
    <message name="CreateItemResponseMessage">
        <part name="payload" element="cit:CreateItemResponse"/>
    </message>
    <message name="GeneralFaultMessage">
        <part name="fault" element="fault:GeneralFault"/>
    </message>
    <portType name="ItemCRUDPortType">
        <operation name="CreateItem">
            <input message="tns:CreateItemRequestMessage"/>
            <output message="tns:CreateItemResponseMessage"/>
            <fault name="GeneralFault" message="tns:GeneralFaultMessage"/>
        </operation>
    </portType>
</definitions>
